[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]
solc_version = "0.8.30"
evm_version = "prague"
optimizer = true
optimizer_runs = 200
# Upgradeable safety validation
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "./"}]

[profile.verify.etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
